import { IDestination, ITrip, IUser, IReview, IGalleryItem } from '@/types';

export const SEED_USERS: IUser[] = [
  {
    id: 'user_1',
    name: 'Aria Montgomery',
    email: 'aria@ghurabo.com',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&q=80&w=400',
    coverImage: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&q=80&w=1200',
    role: 'traveller',
    bio: 'Full-time solo backpacker & landscape photographer. 34 districts explored in Bangladesh!',
    location: 'Dhaka, Bangladesh',
    preferredStyle: 'Solo',
    visitedCount: 18,
    followersCount: 3420,
    followingCount: 215,
    totalHelpfulVotes: 489,
    badges: ['Top Backpacker', 'Verified Explorer', 'Community Guide'],
    createdAt: '2025-01-10T12:00:00Z',
  },
  {
    id: 'user_2',
    name: 'Tanvir & Sarah',
    email: 'tanvir@ghurabo.com',
    avatar: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&q=80&w=400',
    coverImage: 'https://images.unsplash.com/photo-1510414842594-a61c69b5ae57?auto=format&fit=crop&q=80&w=1200',
    role: 'traveller',
    bio: 'Couple travel vloggers seeking hidden gems, luxury eco-resorts, and authentic Bengali cuisine.',
    location: 'Chittagong, Bangladesh',
    preferredStyle: 'Couple',
    visitedCount: 26,
    followersCount: 8900,
    followingCount: 410,
    totalHelpfulVotes: 1250,
    badges: ['Couple Explorers', 'Hotel Reviewer', 'Pro Storyteller'],
    createdAt: '2025-01-15T12:00:00Z',
  },
  {
    id: 'user_admin',
    name: 'Ghurabo Admin',
    email: 'admin@ghurabo.com',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&q=80&w=400',
    coverImage: 'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?auto=format&fit=crop&q=80&w=1200',
    role: 'admin',
    bio: 'Official Ghurabo Community Lead and Quality Moderator.',
    location: 'Dhaka, Bangladesh',
    preferredStyle: 'Group',
    visitedCount: 45,
    followersCount: 15400,
    followingCount: 12,
    totalHelpfulVotes: 5400,
    badges: ['Platform Founder', 'Master Explorer', 'Verified Guide'],
    createdAt: '2025-01-01T12:00:00Z',
  },
];

export const SEED_DESTINATIONS: IDestination[] = [
  {
    id: 'dest_1',
    name: "Cox's Bazar Beach",
    slug: 'coxs-bazar-beach',
    country: 'Bangladesh',
    division: 'Chittagong',
    category: 'Beach',
    image: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&q=80&w=1000',
    heroImage: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&q=80&w=1800',
    description: "The world's longest unbroken natural sea beach spanning 120 km of golden sands, sunset point at Laboni, and scenic marine drive down to Teknaf.",
    bestVisitingTime: 'November - March',
    avgCostSolo: 120,
    avgCostCouple: 250,
    avgCostFamily: 450,
    avgCostGroup: 600,
    avgDurationDays: 4,
    transportInfo: 'Direct AC Bus from Dhaka (8 hrs) or 45-min flight to Cox’s Bazar Airport (CXB). Local TomTom auto-rickshaws available everywhere.',
    safetyTips: 'Always swim in designated safe red/green flag zones. Beware of strong undertow during high tide at Inani.',
    totalTrips: 42,
    avgRating: 4.8,
    isPopular: true,
  },
  {
    id: 'dest_2',
    name: 'Sajek Valley & Clouds',
    slug: 'sajek-valley',
    country: 'Bangladesh',
    division: 'Rangamati',
    category: 'Mountain',
    image: 'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?auto=format&fit=crop&q=80&w=1000',
    heroImage: 'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?auto=format&fit=crop&q=80&w=1800',
    description: 'Queen of hills in Rangamati surrounded by cloud ocean, lush green mountain ridges, tribal culture, Helipad sunset point, and Ruilui Para.',
    bestVisitingTime: 'September - February',
    avgCostSolo: 140,
    avgCostCouple: 280,
    avgCostFamily: 490,
    avgCostGroup: 650,
    avgDurationDays: 3,
    transportInfo: 'Bus to Khagrachari, then hire a Chander Gari (4x4 Jeep) under army escort to Sajek Valley (approx 3.5 hrs).',
    safetyTips: 'Cellular reception is limited. Carry cash as there are no ATMs in Sajek. Carry warm clothes for cool mountain nights.',
    totalTrips: 38,
    avgRating: 4.9,
    isPopular: true,
  },
  {
    id: 'dest_3',
    name: 'Saint Martin Coral Island',
    slug: 'saint-martin-island',
    country: 'Bangladesh',
    division: 'Chittagong',
    category: 'Island',
    image: 'https://images.unsplash.com/photo-1559128010-7c1ad6e1b6a5?auto=format&fit=crop&q=80&w=1000',
    heroImage: 'https://images.unsplash.com/photo-1559128010-7c1ad6e1b6a5?auto=format&fit=crop&q=80&w=1800',
    description: 'Tiny tropical coral island in the northeastern part of the Bay of Bengal featuring crystal blue waters, fresh green coconut groves, and Chera Dwip.',
    bestVisitingTime: 'November - February',
    avgCostSolo: 160,
    avgCostCouple: 320,
    avgCostFamily: 550,
    avgCostGroup: 750,
    avgDurationDays: 3,
    transportInfo: 'Take luxury ship from Teknaf jetty or Cox’s Bazar to St. Martin. Bicycles and rickshaws operate on the island.',
    safetyTips: 'Do not collect or break natural corals. Return to main island before high tide when visiting Chera Dwip.',
    totalTrips: 29,
    avgRating: 4.7,
    isPopular: true,
  },
  {
    id: 'dest_4',
    name: 'Sreemangal Tea Capital',
    slug: 'sreemangal-tea-capital',
    country: 'Bangladesh',
    division: 'Sylhet',
    category: 'Nature',
    image: 'https://images.unsplash.com/photo-1544644181-1484b3fdfc62?auto=format&fit=crop&q=80&w=1000',
    heroImage: 'https://images.unsplash.com/photo-1544644181-1484b3fdfc62?auto=format&fit=crop&q=80&w=1800',
    description: 'Rolling emerald green tea gardens, Lawachara National Park rainforest trails, and the world-famous 7-layer Nilkantha tea.',
    bestVisitingTime: 'July - November',
    avgCostSolo: 90,
    avgCostCouple: 180,
    avgCostFamily: 350,
    avgCostGroup: 480,
    avgDurationDays: 3,
    transportInfo: 'Direct Parabat or Upaban Express train from Dhaka Kamalapur to Sreemangal Station (approx 4.5 hrs).',
    safetyTips: 'Wear high socks and trekking shoes inside Lawachara forest to protect from leeches during rainy season.',
    totalTrips: 24,
    avgRating: 4.8,
    isPopular: true,
  },
  {
    id: 'dest_5',
    name: 'Sundarbans Mangrove Forest',
    slug: 'sundarbans-mangrove',
    country: 'Bangladesh',
    division: 'Khulna',
    category: 'Wildlife',
    image: 'https://images.unsplash.com/photo-1516026672322-bc52d61a55d5?auto=format&fit=crop&q=80&w=1000',
    heroImage: 'https://images.unsplash.com/photo-1516026672322-bc52d61a55d5?auto=format&fit=crop&q=80&w=1800',
    description: 'UNESCO World Heritage largest mangrove forest on earth, home of the majestic Royal Bengal Tiger, spotted deer, and Kotka beach.',
    bestVisitingTime: 'December - February',
    avgCostSolo: 220,
    avgCostCouple: 450,
    avgCostFamily: 800,
    avgCostGroup: 1100,
    avgDurationDays: 4,
    transportInfo: 'Bus or train to Khulna or Mongla port, followed by 3-day guided tourist cruise ship with forest department armed guard.',
    safetyTips: 'Always stay with the official tour group and armed forest guards during canal trekking and watch tower visits.',
    totalTrips: 19,
    avgRating: 4.9,
    isPopular: false,
  },
  {
    id: 'dest_6',
    name: 'Bandarban & Nilgiri Heights',
    slug: 'bandarban-nilgiri',
    country: 'Bangladesh',
    division: 'Chittagong Hill Tracts',
    category: 'Mountain',
    image: 'https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&q=80&w=1000',
    heroImage: 'https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&q=80&w=1800',
    description: 'Highest mountain peaks of Bangladesh, heavenly Nilgiri cloud resort, Boga Lake crater, and pristine Nafakhum waterfall.',
    bestVisitingTime: 'October - March',
    avgCostSolo: 130,
    avgCostCouple: 260,
    avgCostFamily: 480,
    avgCostGroup: 620,
    avgDurationDays: 4,
    transportInfo: 'Direct night coach from Dhaka to Bandarban town, then four-wheel drive Chander Gari for mountain passes.',
    safetyTips: 'Always register at security checkpoints with National ID / Passport. Hire registered local guides for waterfall treks.',
    totalTrips: 31,
    avgRating: 4.9,
    isPopular: false,
  },
];

export const SEED_TRIPS: ITrip[] = [
  {
    id: 'trip_1',
    title: '4 Days Untamed Solo Expedition Along Cox’s Bazar Marine Drive',
    slug: '4-days-solo-coxs-bazar-marine-drive',
    userId: 'user_1',
    userName: 'Aria Montgomery',
    userAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&q=80&w=400',
    destinationId: 'dest_1',
    destinationName: "Cox's Bazar Beach",
    travelDate: '2025-12-10',
    travelType: 'Solo',
    travellersCount: 1,
    durationDays: 4,
    summary: 'A soul-soothing solo journey exploring quiet hidden spots at Himchari, Inani coral beach, and riding a scooter along the scenic Marine Drive highway.',
    story: `I packed my camera gear and took an overnight non-stop sleeper coach from Dhaka directly to Cox’s Bazar. Day 1 started with watching the sunrise at Sugandha beach. The highlight was renting a scooter on Day 2 to ride down the 80 km Marine Drive. Inani beach offered peaceful coral tide pools where I spent hours capturing long-exposure photographs. The locals were extraordinarily welcoming, and sunset dinners by Kolatoli made this one of my most memorable solo expeditions.`,
    highlights: ['Sunset photography at Inani coral beach', 'Scooter ride along Marine Drive', 'Fresh grilled pomfret at Kolatoli market'],
    tips: 'Rent scooters early morning at Kolatoli main junction for better rates. Bring a waterproof phone pouch for beach walks.',
    safetyNotes: 'Avoid solo night rides along unlit segments after 9 PM. Always check tide timings before walking near cliffs.',
    coverImage: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&q=80&w=1200',
    images: [
      { url: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&q=80&w=1200', caption: 'Golden sunset glow over Laboni' },
      { url: 'https://images.unsplash.com/photo-1510414842594-a61c69b5ae57?auto=format&fit=crop&q=80&w=1200', caption: 'Marine drive open coastline' },
    ],
    costBreakdown: {
      transport: 35,
      hotel: 45,
      food: 25,
      localTransport: 15,
      tickets: 5,
      guide: 0,
      shopping: 10,
      misc: 5,
      totalCost: 140,
      perPersonCost: 140,
    },
    itinerary: [
      { dayNumber: 1, title: 'Arrival & Beach Walk', activities: ['Arrive via AC Bus', 'Sugandha beach sunset walk', 'Grilled fish dinner'], locations: ['Coxs Bazar'], estimatedCost: 30 },
      { dayNumber: 2, title: 'Marine Drive & Inani', activities: ['Rent scooter', 'Drive along Marine Highway', 'Explore Inani coral tide pools'], locations: ['Himchari', 'Inani'], estimatedCost: 45 },
      { dayNumber: 3, title: 'Teknaf Frontier & Salt Flats', activities: ['Cruise down towards Teknaf', 'Visit local fishing villages'], locations: ['Teknaf'], estimatedCost: 40 },
      { dayNumber: 4, title: 'Souvenirs & Departure', activities: ['Burmese Market shopping', 'Afternoon return journey'], locations: ['Kolatoli'], estimatedCost: 25 },
    ],
    status: 'approved',
    isVerified: true,
    isPopular: true,
    likesCount: 142,
    savesCount: 68,
    helpfulVotesCount: 54,
    commentsCount: 12,
    ratings: { overall: 4.9, safety: 4.8, cleanliness: 4.7, transport: 5.0, accommodation: 4.8, food: 5.0, value: 5.0 },
    createdAt: '2025-12-15T08:00:00Z',
  },
  {
    id: 'trip_2',
    title: '3 Days Couple Cloud Getaway in Sajek Valley Mountain Cottages',
    slug: '3-days-couple-sajek-valley-clouds',
    userId: 'user_2',
    userName: 'Tanvir & Sarah',
    userAvatar: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&q=80&w=400',
    destinationId: 'dest_2',
    destinationName: 'Sajek Valley & Clouds',
    travelDate: '2025-11-20',
    travelType: 'Couple',
    travellersCount: 2,
    durationDays: 3,
    summary: 'A breathtaking romantic getaway waking up above a sea of clouds in Ruilui Para cottage, experiencing Helipad sunsets, and tasting bamboo chicken.',
    story: `We booked a cliffside wooden resort 3 weeks in advance. The journey from Khagrachari with the army convoy escort felt like a thrilling expedition. When we reached Sajek at noon, clouds were gently rolling into our private balcony! At night, the sky was filled with thousands of visible stars. Trying authentic bamboo chicken at a local tribal kitchen was the culinary highlight of our trip.`,
    highlights: ['Cloud ocean view directly from resort balcony', 'Stargazing at Helipad 2', 'Traditional bamboo chicken dinner'],
    tips: 'Pre-book wooden cliffside resorts at least 3 weeks in advance for peak winter weekends.',
    safetyNotes: 'Always follow the morning or afternoon army escort schedule when leaving Khagrachari.',
    coverImage: 'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?auto=format&fit=crop&q=80&w=1200',
    images: [
      { url: 'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?auto=format&fit=crop&q=80&w=1200', caption: 'Sunrise cloud ocean at Sajek' },
      { url: 'https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&q=80&w=1200', caption: 'Mountain cottage viewpoint' },
    ],
    costBreakdown: {
      transport: 60,
      hotel: 140,
      food: 50,
      localTransport: 40,
      tickets: 5,
      guide: 0,
      shopping: 20,
      misc: 15,
      totalCost: 330,
      perPersonCost: 165,
    },
    itinerary: [
      { dayNumber: 1, title: 'Convoy Ride & Sunset', activities: ['Army convoy from Khagrachari', 'Check-in to resort', 'Sunset at Helipad 1'], locations: ['Sajek'], estimatedCost: 120 },
      { dayNumber: 2, title: 'Konglak Pahar Trek', activities: ['Early morning cloud viewing', 'Trek to highest Konglak peak', 'Bamboo tea & tribal snacks'], locations: ['Konglak'], estimatedCost: 130 },
      { dayNumber: 3, title: 'Alutila Cave & Return', activities: ['Return escort to Khagrachari', 'Explore Alutila cave with flaming torch', 'Night coach return'], locations: ['Khagrachari'], estimatedCost: 80 },
    ],
    status: 'approved',
    isVerified: true,
    isPopular: true,
    likesCount: 289,
    savesCount: 145,
    helpfulVotesCount: 118,
    commentsCount: 24,
    ratings: { overall: 5.0, safety: 4.9, cleanliness: 4.8, transport: 4.6, accommodation: 5.0, food: 4.9, value: 4.8 },
    createdAt: '2025-11-25T10:00:00Z',
  },
  {
    id: 'trip_3',
    title: 'Weekend Escape to Sreemangal Lush Tea Gardens & Rainforest Trails',
    slug: 'weekend-escape-sreemangal-tea-gardens',
    userId: 'user_1',
    userName: 'Aria Montgomery',
    userAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&q=80&w=400',
    destinationId: 'dest_4',
    destinationName: 'Sreemangal Tea Capital',
    travelDate: '2025-10-05',
    travelType: 'Solo',
    travellersCount: 1,
    durationDays: 3,
    summary: 'Riding vintage bicycles through endless tea valleys, trekking inside Lawachara National Park, and sipping 7-layer tea at Nilkantha cabin.',
    story: `The morning train ride from Dhaka was calm and refreshing. Sreemangal greeted me with cool breezy air and soothing shades of green. I rented a bicycle to navigate through Finlay and Zareen tea estates. In the afternoon, a trek inside Lawachara national park gave me glimpses of rare Hoolock Gibbons and barking deers. A deeply relaxing green detox!`,
    highlights: ['Bicycle ride through tea gardens', 'Hoolock Gibbon sighting in Lawachara', 'Seven layer tea experience'],
    tips: 'Rent a bicycle or electric rickshaw to tour the estates at your own pace.',
    safetyNotes: 'Wear leech socks when venturing deep into rainforest trails during rainy or post-monsoon months.',
    coverImage: 'https://images.unsplash.com/photo-1544644181-1484b3fdfc62?auto=format&fit=crop&q=80&w=1200',
    images: [
      { url: 'https://images.unsplash.com/photo-1544644181-1484b3fdfc62?auto=format&fit=crop&q=80&w=1200', caption: 'Tea estate slopes in Sreemangal' },
    ],
    costBreakdown: {
      transport: 18,
      hotel: 40,
      food: 20,
      localTransport: 10,
      tickets: 5,
      guide: 10,
      shopping: 15,
      misc: 5,
      totalCost: 123,
      perPersonCost: 123,
    },
    itinerary: [
      { dayNumber: 1, title: 'Train Arrival & Tea Trails', activities: ['Parabat Express train', 'Bicycle ride through Finlay estate'], locations: ['Sreemangal'], estimatedCost: 35 },
      { dayNumber: 2, title: 'Lawachara & Khasia Village', activities: ['Rainforest morning trek', 'Khasia tribal village visit', 'Seven-layer tea'], locations: ['Lawachara'], estimatedCost: 55 },
      { dayNumber: 3, title: 'Baikka Beel & Departure', activities: ['Birdwatching at Baikka Beel wetland', 'Fresh tea leaf shopping', 'Return train'], locations: ['Baikka Beel'], estimatedCost: 33 },
    ],
    status: 'approved',
    isVerified: true,
    isPopular: true,
    likesCount: 175,
    savesCount: 92,
    helpfulVotesCount: 68,
    commentsCount: 9,
    ratings: { overall: 4.8, safety: 5.0, cleanliness: 4.9, transport: 4.8, accommodation: 4.7, food: 4.8, value: 5.0 },
    createdAt: '2025-10-10T14:00:00Z',
  },
];

export const SEED_GALLERY: IGalleryItem[] = [
  {
    id: 'gal_1',
    url: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&q=80&w=1200',
    caption: 'Golden hour sunset over Cox’s Bazar Laboni coastline',
    tripId: 'trip_1',
    tripTitle: '4 Days Untamed Solo Expedition Along Cox’s Bazar Marine Drive',
    tripSlug: '4-days-solo-coxs-bazar-marine-drive',
    destinationName: "Cox's Bazar Beach",
    travelType: 'Solo',
    photographerName: 'Aria Montgomery',
    photographerAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&q=80&w=400',
    photographerId: 'user_1',
    likesCount: 98,
    createdAt: '2025-12-15T08:00:00Z',
  },
  {
    id: 'gal_2',
    url: 'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?auto=format&fit=crop&q=80&w=1200',
    caption: 'Cloud ocean sunrise from Sajek Helipad peak',
    tripId: 'trip_2',
    tripTitle: '3 Days Couple Cloud Getaway in Sajek Valley Mountain Cottages',
    tripSlug: '3-days-couple-sajek-valley-clouds',
    destinationName: 'Sajek Valley & Clouds',
    travelType: 'Couple',
    photographerName: 'Tanvir & Sarah',
    photographerAvatar: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&q=80&w=400',
    photographerId: 'user_2',
    likesCount: 145,
    createdAt: '2025-11-25T10:00:00Z',
  },
  {
    id: 'gal_3',
    url: 'https://images.unsplash.com/photo-1544644181-1484b3fdfc62?auto=format&fit=crop&q=80&w=1200',
    caption: 'Morning mist settling over Sreemangal emerald tea slopes',
    tripId: 'trip_3',
    tripTitle: 'Weekend Escape to Sreemangal Lush Tea Gardens & Rainforest Trails',
    tripSlug: 'weekend-escape-sreemangal-tea-gardens',
    destinationName: 'Sreemangal Tea Capital',
    travelType: 'Solo',
    photographerName: 'Aria Montgomery',
    photographerAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&q=80&w=400',
    photographerId: 'user_1',
    likesCount: 82,
    createdAt: '2025-10-10T14:00:00Z',
  },
  {
    id: 'gal_4',
    url: 'https://images.unsplash.com/photo-1559128010-7c1ad6e1b6a5?auto=format&fit=crop&q=80&w=1200',
    caption: 'Turquoise ocean water washing against Saint Martin live corals',
    tripId: 'trip_1',
    tripTitle: 'Saint Martin Tropical Coral Island',
    tripSlug: 'saint-martin-island',
    destinationName: 'Saint Martin Coral Island',
    travelType: 'Solo',
    photographerName: 'Tanvir & Sarah',
    photographerAvatar: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&q=80&w=400',
    photographerId: 'user_2',
    likesCount: 110,
    createdAt: '2025-09-12T11:00:00Z',
  },
  {
    id: 'gal_5',
    url: 'https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&q=80&w=1200',
    caption: 'High mountain ridge and winding roads of Bandarban',
    tripId: 'trip_2',
    tripTitle: 'Bandarban & Nilgiri Heights',
    tripSlug: 'bandarban-nilgiri',
    destinationName: 'Bandarban & Nilgiri Heights',
    travelType: 'Couple',
    photographerName: 'Ghurabo Admin',
    photographerAvatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&q=80&w=400',
    photographerId: 'user_admin',
    likesCount: 160,
    createdAt: '2025-08-05T09:00:00Z',
  },
  {
    id: 'gal_6',
    url: 'https://images.unsplash.com/photo-1510414842594-a61c69b5ae57?auto=format&fit=crop&q=80&w=1200',
    caption: 'Sunset waves breaking across sandy coastal shores',
    tripId: 'trip_1',
    tripTitle: '4 Days Untamed Solo Expedition Along Cox’s Bazar Marine Drive',
    tripSlug: '4-days-solo-coxs-bazar-marine-drive',
    destinationName: "Cox's Bazar Beach",
    travelType: 'Solo',
    photographerName: 'Aria Montgomery',
    photographerAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&q=80&w=400',
    photographerId: 'user_1',
    likesCount: 76,
    createdAt: '2025-12-16T15:00:00Z',
  },
];

export const SEED_REVIEWS: IReview[] = [
  {
    id: 'rev_1',
    tripId: 'trip_1',
    destinationId: 'dest_1',
    userId: 'user_2',
    userName: 'Tanvir & Sarah',
    userAvatar: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&q=80&w=400',
    overallRating: 5,
    ratings: { safety: 5, cleanliness: 4, transport: 5, accommodation: 5, food: 5, value: 5 },
    comment: 'Super accurate breakdown! The scooter rental tip saved us a lot of hassle. Inani sunset is definitely unbeatable.',
    createdAt: '2025-12-20T10:00:00Z',
  },
];
